# 로컬환경에서만 사용하기

#spring:
#  profiles: local
#server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 8443